### ISSUE TITLE
TerminatingError(): "You cannot call a method on a null-valued expression." - Microsoft Update Catalog Drivers

### ISSUE THREAD

**Issue by njmulder** [OSDeploy/OSDCloud#35]
Terminating Error when at the Microsoft Update Catalog Drivers Stage:

=========================================================================
2024-03-11-103834
Microsoft Update Catalog Drivers
Drivers for PNPClass DiskDrive will be downloaded from Microsoft Update Catalog to C:\Drivers\MsUpCatDrivers
Devices were found for PNPClass DiskDrive
DeviceID: USBSTOR\DISK&VEN_GENERIC&PROD_MASSSTORAGECLASS&REV_1536\000000001536&0
HardwareID: USBSTOR\DiskGeneric_MassStorageClass1536
DeviceID: USBSTOR\DISK&VEN_GENERIC&PROD_MASSSTORAGECLASS&REV_1536\000000001536&1
HardwareID: USBSTOR\DiskGeneric_MassStorageClass1536
DeviceID: SCSI\DISK&VEN_NVME&PROD_SAMSUNG_MZVLB512\5&1EA98805&0&000000
HardwareID: SCSI\DiskNVMe__________________SAMSUNG_MZVLB512HBJQ-000L75M2QEXF7
DeviceID: USBSTOR\DISK&VEN_SANDISK&PROD_ULTRA&REV_1.00\4C530001290611109484&0
HardwareID: USBSTOR\DiskSanDisk_Ultra___________1.00
Drivers for PNPClass Net will be downloaded from Microsoft Update Catalog to C:\Drivers\MsUpCatDrivers
Devices were found for PNPClass Net
DeviceID: PCI\VEN_8086&DEV_02F0&SUBSYS_00708086&REV_00\3&11583659&0&A3
Searching: VEN_8086&DEV_02F0
Net Intel(R) Wi-Fi 6 AX201 160MHz
HardwareID: VEN_8086&DEV_02F0
SearchString: VEN_8086%26DEV_02F0
Intel - net - 23.20.1.1 version n/a
Version n/a Size: 13.6 MB
Last Updated 12/19/2023 10:38:45
UpdateID: 2a3f7acc-5099-4c20-a06b-0bdd9cdd77e1
Downloading and expanding to C:\Drivers\MsUpCatDrivers\2a3f7acc-5099-4c20-a06b-0bdd9cdd77e1
https://catalog.s.download.windowsupdate.com/c/msdownload/update/driver/drvs/2024/01/5d37848c-7c9e-426d-8b92-cc9b27e694ae_0b505d19430b2f99df68beb10770cb4c562bcb6d.cab
DeviceID: ROOT\KDNIC\0000
HardwareID: root\kdnic
DeviceID: USB\VID_0B95&PID_1790\00000000000CC2
Searching: VID_0B95&PID_1790
Net ASIX AX88179A USB 3.2 Gen1 to Gigabit Ethernet Adapter
HardwareID: VID_0B95&PID_1790
SearchString: VID_0B95%26PID_1790
ASIX - Net - 2.22.7.0 version n/a
Version n/a Size: 86 KB
Last Updated 08/01/2023 10:38:49
UpdateID: a592b9db-b463-4842-b2a2-90facf75b8ee
Downloading and expanding to C:\Drivers\MsUpCatDrivers\a592b9db-b463-4842-b2a2-90facf75b8ee
https://catalog.s.download.windowsupdate.com/c/msdownload/update/driver/drvs/2023/09/ecbf41cf-8912-4282-993b-da94308f548b_9cc6586d8b289c576366f0094df20a78b9da5c9f.cab
DeviceID: PCI\VEN_8086&DEV_0D4F&SUBSYS_22AF17AA&REV_00\3&11583659&0&FE
Searching: VEN_8086&DEV_0D4F
Net Intel(R) Ethernet Connection (10) I219-V
HardwareID: VEN_8086&DEV_0D4F
SearchString: VEN_8086%26DEV_0D4F
Intel - Net - 12.19.2.57 version n/a
Version n/a Size: 286 KB
Last Updated 11/24/2023 10:38:53
UpdateID: 96a223c4-3e7c-4679-a5c9-647f9f13f9cb
Downloading and expanding to C:\Drivers\MsUpCatDrivers\96a223c4-3e7c-4679-a5c9-647f9f13f9cb
https://catalog.s.download.windowsupdate.com/d/msdownload/update/driver/drvs/2024/02/7b614b3d-b07c-46bb-88d0-ed72d53a214b_61d4ee4abafbfbb1d660fef541a67cfc3273c66b.cab
DeviceID: ROOT\NDISVIRTUALBUS\0000
HardwareID: ROOT\NdisVirtualBus
Drivers for PNPClass SCSIAdapter will be downloaded from Microsoft Update Catalog to C:\Drivers\MsUpCatDrivers
Devices were found for PNPClass SCSIAdapter
DeviceID: ROOT\SPACEPORT\0000
HardwareID: Root\Spaceport
DeviceID: PCI\VEN_144D&DEV_A808&SUBSYS_A801144D&REV_00\4&141551D8&0&00EC
Searching: VEN_144D&DEV_A808
PS>TerminatingError(): "You cannot call a method on a null-valued expression."
>> TerminatingError(): "You cannot call a method on a null-valued expression."
>> TerminatingError(): "You cannot call a method on a null-valued expression."
>> TerminatingError(): "You cannot call a method on a null-valued expression."
>> TerminatingError(): "You cannot call a method on a null-valued expression."
>> TerminatingError(): "You cannot call a method on a null-valued expression."
>> TerminatingError(): "You cannot call a method on a null-valued expression."
>> TerminatingError(): "You cannot call a method on a null-valued expression."
You cannot call a method on a null-valued expression.
You cannot call a method on a null-valued expression.
At X:\Program Files\WindowsPowerShell\Modules\OSD\24.2.20.1\Classes\MsUpCatResponse.Class.ps1:11 char:9
+         $this.Rows = $Table.SelectNodes("tr")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

PS>$global:?
False
**********************
Windows PowerShell transcript end
End time: 20240311103856
**********************

**Comment by njmulder** [comment]
This looks like it's been resolved with the roll out of OSD version 24.3.10.1

**Comment by emile1920** [comment]
Hi @njmulder ,

Apologies in advance, Im new to github protical, so if i make a foh pah in github etiquite please say!

You mentioned this has been resolved, Im still encountering the issue on our build image. I had belived that OSD cloud pulled in the latest module within the PE enviroment. 
We are still encountering the same issue as you orginally did. Did you have to rebuild the image to resolve it? 

Many Thanks in advance!
